.eslintrc.js
README.md
client/api/course.js
client/components/editor/toolbar/index.vue
client/store/helpers/collection.js
client/utils/auth.js
client/utils/calculatePosition.js
client/utils/numberToLetter.js
config/shared/activities.js
config/utils/configLoader.js
package-lock.json
package.json
server/activity/index.js
server/comment/channel.js
server/course/course.controller.js
server/course/index.js
server/revision/index.js
server/shared/database/seed/index.js
server/shared/storage/helpers.js
server/shared/storage/providers/amazon.js
server/shared/util/sse.js

This PR introduces following changes:
- using [semistandard](https://github.com/Flet/eslint-config-semistandard) ESLint config as base 🏄 
- migrating from babel-eslint to espree (espree is default ESLint parser, faster and supports all es features we use)
- disabling errors on promise/method invocation chains (fine tuning ESLint's `indent` rule) :tada:
- removing extra semicolons :goat:
- moar badges 🕶

ESLint fine-tuning 

---

config/client/poi.config.js

This PR addresses incorrect webpack config defaults generated by poi. Poi adds absolute path to local `node_modules` to module resolution config thus causing webpack to search for 2nd row dependencies (dependencies of dependencies) inside local `node_modules` 🤦‍♂️ 
This caused build errors in on recent version of `develop` due to having `auto-bind` as both `tailor` and `vuex-module` dependency...

Fixing incorrect module resolution (webpack)

---

.activities-rc.json.example

Per the new [schema validation](https://github.com/ExtensionEngine/tailor/blob/develop/config/shared/schema-validation.js#L20) a label is required for for the activities structures, and the example won't work out-of-the-box without it.

Add label to activity example schema

---

server/shared/publishing/helpers.js

The `versionedAt` property represents a date which is updated whenever
something gets published inside a specific repository. It is a
compliment to the `version` property, which is a hash representation of
the same thing.
Another difference is that the `versionedAt` property is included inside
the repository catalog info as well.

Add the `versionedAt` property to the published repository info

---

client/components/editor/toolbar/EmbedToolbar.vue
package-lock.json

- Fixes #98 
- Minimum `iframe` height is lowered to 50 pixels whereas default one is left at 300 pixels.

Lower minimum embed element height

---

client/components/course/Outline/InsertActivity/index.vue

This resolves #97 .
When adding a new activity on the outline below another activity, that upper activity will now expand only if the newly added activity is its child.

Expand upper activity on outline only if new activity is its child

---

build/plugins/stats.js
package-lock.json
package.json

This PR alters behaviour of local poi stats plugin in order to generate stats inside _root_ dir instead of `dist`. This uses same approach as [`poi@9`](https://github.com/egoist/poi/blob/6d3c7ff/packages/poi/bin/run.js#L125-L134) :tada:

Generate `stats.json` inside root directory

---

client/components/editor/structure/ContentContainers/index.vue

Note: this only creates the content container when it's first opened;
it's still possible to delete all the content containers by hand and
then create the first one manually (which can be useful for users who
wish to drop their current work and start over).

Create a content container by default, if one does't exist

---

package-lock.json
package.json
server/activity/activity.model.js
server/activity/index.js
server/comment/comment.model.js
server/comment/hooks.js
server/comment/index.js
server/course/course.controller.js
server/course/course.model.js
server/course/hooks.js
server/course/index.js
server/revision/hooks.js
server/revision/index.js
server/revision/revision.model.js
server/shared/auth/index.js
server/shared/database/hooks.js
server/shared/database/index.js
server/shared/util/addHooks.js
server/shared/util/processListQuery.js
server/teaching-element/te.controller.js
server/teaching-element/te.model.js
server/user/user.controller.js

This PR upgrades [`sequelize`](https://npm.im/sequelize) to v5 and introduces changes to `scopes` and `hooks` handling :tada:

Upgrade sequelize to v5

---

client/App.vue

So apparently a part of the Vuetify's (questionable) design is to set
`overflow-y: scroll` on an `html` element, which makes the scrollbar
visible even when there is no overflowing content.
See this issue for more info: https://github.com/vuetifyjs/vuetify/issues/864
Note: Mac users probably don't notice this issue, because MacOS hides
the scrollbar by default if there's no mouse connected to it.

Remove the always showing scrollbar on an html element set by Vuetify

---

.env.example
.gitignore

This PR sets default filesystem storage provider output area to `./data` directory which has been included in `.gitignore`.

Ignore filesystem provider storage area

---

package-lock.json
package.json
server/shared/database/index.js

This PR fixes postegres version checking by adding version constraint to `package.json` `engines` map and adding missing `semver` dependency. :bug:

Fix postgres version check

---

.env.example
server/shared/logger.js

This PR provides developer to set [bunyan](https://www.npmjs.com/package/bunyan#levels) logger `level`. Suggestion is to set level type `'debug'`. Reason for that is, for example: when developer is querying database, it will display query logs in terminal which can be very helpful.

Logger modification

---

client/components/common/InputAsset.vue

`InputAssets` component is now extended with `allowFileUpload` prop to determine if `file-upload` component should be rendered. Additionally, placeholder text for URL input field is changed depending on the prop. `allowFileUpload` defaults to `true` to preserve current behaviour.

Extend InputAsset component to accept additional prop

---

.eslintrc.js
package-lock.json
package.json
poi.config.js
server/.eslintrc.js
stylelint.config.js

This PR adds type annotations to `poi` and `stylelint` configurations in order to enable easier editing inside VS Code :rocket:

Add JSDoc types to configuration objects

---

server/shared/database/migrations/20181115140901-create-user.js
server/shared/database/migrations/20181115140902-create-course.js
server/shared/database/migrations/20181115140903-course-user-relationship.js
server/shared/database/migrations/20181115140904-create-activity.js
server/shared/database/migrations/20181115140905-create-teaching-element.js
server/shared/database/migrations/20181115140906-create-revision.js
server/shared/database/migrations/20181115140907-create-comment.js
server/shared/database/migrations/20181115140943-add-meta-to-teaching-element.js
server/shared/database/migrations/20190416152610-change-table-cell-type.js

This PR alters migration code format. Instead of using joint `module.exports` separate `exports` are being used 🦊

Reformat migration files

---

server/shared/publishing/helpers.js

This PR fixes an issue with assessments publishing. Assessments stay published even if they are deleted. The solution was to remove empty assessments check before saveFile, so no assessments result in an empty file.

TA-389 - Assessments publishing issue fix

---

client/components/common/Meta/BaseSelect.vue
client/components/common/Meta/Multiselect.js
client/components/common/Meta/Select.js
client/components/common/Meta/index.vue
package-lock.json

This PR adds `MULTISELECT` meta type.
The reasoning behind adding a new meta type instead of adding an option to existing `SELECT` meta type:
- to preserve published value types consistency (`SELECT` produces a single value, while `MULTISELECT` produces an Array of values)
- ease out LMS/consumer data parsing
- avoid possible breaks of backward compatibility for existing `SELECT` meta type

Add Multiselect meta type

---

client/main.js
package-lock.json
package.json

On some cases of `npm install`, `vue-directive-tooltip` set to `^1.4.2` in `package.json` would install latest version `1.6.2` which has a different folder structure and import of the .css file in `client/main.js` would break.
Dependency isn't used anymore so it can be removed.

Rremove unused vue-directive-tooltip

---

client/components/common/Select.vue

Before:
After:
I went through all the (multi)select elements that I could find and none of them seem to be broken after this change.

Fix multiselect placeholder overlay

---

server/shared/database/migrations/20190416152610-change-table-cell-type.js

This PR alters `20190416152610-change-table-cell-type.js` migration in order to eliminate raw SQL queries and external dependencies. Raw queries are replaced with `QueryInterface` method calls :tada:

Refactor change table cell migration

---

config/shared/activities.js

The same tesMeta can be shared between different types of teaching elements

Support multiple types in tes meta configuration

---

server/shared/storage/helpers.js

Setting ACL grant to `public read` would result in an 'Access denied' error when trying to save an image to a bucket which is blocking public access.

Removed ACL grant option on image save

---

client/components/editor/structure/AssessmentItem.vue

This PR removes double truncate on assessment item question (it was truncated both when computed and in the template by truncate filter).

Remove double truncate on AssessmentItem

---

client/components/common/tce-core/AddElement/index.vue

Removed lazy from v-dialog since dynamic component loading impacts vuedraggable.

Removed lazy bottom sheet dialog

---

server/shared/storage/helpers.js

E.g. a data object in the format of:
```js
{
assets: { 'a.b': 'storage://some.url' }
}
```
would after resolving be:
```js
{
assets: { 'a.b': 'storage://url' },
a: { b: 'http://prefix/url' }
}
```

Resolve storage asset keys as JSON paths

---

server/shared/content-plugins/containerRegistry.js
server/shared/publishing/helpers.js

This PR adds the option to export `buildSummary` method from custom containers `util.js` to allow the custom container to build a custom container summary in the published content outline.
If no method is supplied generic summary fallback is used.
Example use-case: Custom container has sub-containers that need to be surfaced to container summary in the outline.

Allow custom container summary

---

client/store/helpers/resource.js
client/store/modules/comments/actions.js
client/store/modules/comments/mutations.js

I wish to resolve #408 
Bug flow and causes: 
1. SSE event is triggered -> all the suscribers have the new comment in state
2. The user focuses and clicks on the competency -> fetch is triggered
3. Fetch gets the data from the endpoint that includes the comment already put in the state by the SSE
4. Fetch inserts the fetched comments in the state 
5. The comment is then duplicated
Fix:
On the step 3. we scan for the comments that are already in the state and we filter them from the fetch before its triggered. That way we don't put the comments that are already in the state.
@kjuej @underscope Please check if the solution is satisfactionary and where the improvements are to be made. Thx.

Remove existing comments from fetch

---

client/components/repository/Revisions/EntityRevisions.vue
package.json
server/script/fixRevisionUrls.js
server/shared/database/index.js

Because of `afterCreate` and `afterUpdate` hooks being added to the Content Element model, the revisions were storing the resolved statics URL. This PR introduces a temporary fix for this issue by switching the order in which the hooks are registered so the Revision hooks are always triggered before the Content Element hooks. The plan is to introduce a system for hooks that will make these hacky solutions unnecessary.
This PR also introduces a script that fixes Revision URLs.

Fixed revision URLs

---

client/components/repository/Outline/reorderMixin.js
client/components/repository/common/Sidebar/Relationship.vue

Invalid mappings led to non-working activity reorder & relationships.
@kjuej ☝️

Fixed issues with store mappings

---

nodemon.json

`data` directory should be ignored by nodemon if it is reserved for filesystem publishing.

Update nodemon config

---

server/shared/storage/providers/filesystem.js

`mkdirp` API change went unnoticed during the latest snyk PR merge.

mkdirp bugfix

---

client/components/common/Meta/Html.vue

This PR 
- adds the ability to pass Quill editor options (e.g. `toolbar.modules`) to   Quill editor used in HTML meta
- removes unused prop `quillOptions` in favor of `meta.options`
- fixes broken reference
Note: I think we could've made sensible defaults and make it more strict, but this way we don't change existing behavior and add flexibility while we don't deprecate it in favor of Jodit Meta 🤞 
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After<strong></td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Improve HTML meta

---

client/components/common/tce-core/ElementToolbar.vue

Fixes this (matching question is selected in editor but "Numerical Response" is displayed in toolbar):

Element toolbar bugfix

---

client/components/common/Navbar.vue

Make logo and title a tag

---

client/components/common/tce-core/ElementList.vue

This PR:
- Fixes `tce-core`'s `ElementList` passing wrong argument to `getElementId` method when generating list item keys

Fix tce-core element list items key generation

---

README.md
client/components/repository/Outline/Activity.vue
client/components/repository/Outline/OutlineFooter.vue
client/components/repository/Outline/index.vue
client/components/repository/common/ActivityOptions/Menu.vue
client/components/repository/common/ActivityOptions/Toolbar.vue
client/components/repository/common/ActivityOptions/common.js
client/components/repository/common/CopyActivity/index.vue
client/components/repository/common/CreateDialog/TypeSelect.vue
client/components/repository/common/CreateDialog/index.vue
client/components/repository/common/Sidebar/Header.vue
client/components/system-settings/StructureTypes.vue
client/store/modules/repository/activities/getters.js
client/utils/activity.js
client/utils/revision.js
config/shared/activities-rc.js
config/shared/schema-validation.js

This PR improves schema configurability:
- Adds the ability for the same type to exist on multiple levels
- Type recursion (type can be nested within itself/support for dir like structure)
🚨 Breaking changes
1. Omited level property from activity configuration
2. Added `rootLevel` flag to activity configuration to signalize root activities
Example schema:
```javascript
const ACTIVITY_TYPE = {
MODULE: 'MODULE',
LESSON: 'LESSON',
CONTENT_PAGE: 'CONTENT_PAGE'
}
const MODULE = {
type: ACTIVITY_TYPE.MODULE,
rootLevel: true,
label: 'Module',
color: '#5187C7',
subLevels: [
ACTIVITY_TYPE.MODULE,
ACTIVITY_TYPE.LESSON,
ACTIVITY_TYPE.CONTENT_PAGE
]
};
const LESSON = {
type: ACTIVITY_TYPE.LESSON,
rootLevel: true,
label: 'Lesson',
color: '#606F7B',
subLevels: [
ACTIVITY_TYPE.CONTENT_PAGE
]
};
const …
```

Improved schema configurability

---

client/components/content-elements/tce-carousel/edit/index.vue

This PR sets `v-carousel` `height` property explicitly thus fixing the issue https://github.com/ExtensionEngine/tailor/issues/532 in which setting the height of an element did nothing, since default `v-carousel` height would be set to `500px`.

Set v-carousel height explicitly

---

client/components/content-elements/tce-carousel/edit/index.vue

This PR:
- sorts `tce-carousel` items indices numerically and removes reversing of the array
- uses last index in `indices` array when new slide is created which fixes the issue where last slide would be removed instead of current one
- fixes issue https://github.com/ExtensionEngine/tailor/issues/534

Sort carousel item indices numerically

---

client/components/repository/index.vue

- now correctly select an activity after navigation from a tab without activity  (reverted parts of changes made in #560)

Fixed activity selection in outline:

---

server/activity/activity.model.js

Transaction in the `Activity.remove` method wasn't passed to its Sequelize calls which would cause them to not rollback in case of an error.

Fix unused transaction in Activity.remove method

---

client/components/common/tce-core/ElementList.vue
client/components/common/tce-core/EmbeddedContainer.vue

I went with prop drilling (I still don't approve this), it's KISS, it should be enough to support existing content element system.

Introduce add element options on element list and container
