ExtensionEngine/tailor

- server/course/course.model.js
- server/shared/publishing/helpers.js
> Publishing schema and meta within repository root

- server/shared/publishing/helpers.js
> Fixed issue with duplicated fields upon publish

- README.md
- config/shared/activities.js
- server/activity/activity.controller.js
- server/course/course.controller.js
> Default meta support

- client/components/course/settings/General.vue
> Fixed issue with description overflow 

- .env.example
- README.md
- config/client/poi.config.js
- config/shared/activities-rc.js
- package-lock.json
- package.json
> Control seed schema availability

- package-lock.json
- package.json
Bumping [`vuex-module`](https://npm.im/vuex-module) to `0.4.0` :arrow_up:
> Update vuex-module to latest version

- README.md
- unifying badge style
- adding package version badge
- pointing codacy badge to develop branch
- adding opensource ❤️ badge
> Badges spring cleaning

- package-lock.json
- package.json
- server/teaching-element/te.model.js
Using [`hash-obj`](https://npm.im/hash-obj) instead of [`hasha`](https://npm.im/hasha) for content hash calculation to make sure keys insertion order does not mess up calculation.
> Use safe object hash

- client/components/course/InsertActivity/CreateActivity.vue
> Activity creation issue

- client/components/course/Sidebar/Discussion/index.vue
> Issue with comment input

- client/components/editor/teaching-elements/Video.vue
> Keep video element height upon focus

- server/shared/database/seed/index.js
- Fixes #54 
- Will use first custom schema in case that default schema is disabled and custom schema is provided
> Ability to use custom schema for seed

- server/index.js
Implements dangerously awesome welcome message full of usefulness 😂 
[![asciicast](https://asciinema.org/a/09DCC2MlE3YmAgjruXokryEjH.png)](https://asciinema.org/a/09DCC2MlE3YmAgjruXokryEjH)
> Awesome welcome message

- server/course/hooks.js
> Update objective count upon cloning

- package-lock.json
- package.json
- server/script/preflight.js
This PR implements runtime checking of node version before starting application server. 🎉 
Check it out in action:
[![asciicast](https://asciinema.org/a/W2wikJspqGcHAEmcCD6kWGpK9.png)](https://asciinema.org/a/W2wikJspqGcHAEmcCD6kWGpK9)
⚠️ _Screencast shows intentional false positive produced to showcase script's output._
> Server preflight script

- package.json
- server/index.js
- using preflight for all npm scripts
- printing welcome message to stderr
> Tweak npm scripts & app start

- client/components/course/Revisions/RevisionItem.vue
> Fixed issue with revision overflow

- package-lock.json
- package.json
- server/course/course.model.js
> Issue with repository cloning

- server/router.js
- server/user/index.js
- server/user/user.controller.js
- server/user/user.model.js
Making sure all emails are stored lowercase. Processing submission data for public forms (login, forgot & reset password) so we end up with _lowercased_ database queries.
:construction: This probably needs migration script to lowercase emails of existing users. :warning:
> Fix case sensitive emails

- client/components/course/InsertActivity/index.vue
- client/utils/activity.js
> Issue with activity type options upon creation

- client/components/editor/structure/Exams/AssessmentGroup.vue
> Fixed issue with exam assessment margin

- client/components/editor/teaching-elements/Embed.vue
> Fix TeEmbed overlay placeholder positioning

- client/components/course/Revisions/EntityRevisions.vue
- client/components/course/Revisions/index.vue
- client/utils/revision.js
- server/revision/revision.controller.js
- If there are different entities with same id they will appear within a list of particular element
- Resolved by adding entity cond
> Issue with incorrect element revision list

- client/components/course/Outline/NoActivities.vue
- package-lock.json
- package.json
- This PR resolves UI issues with `vue-multiselect`
- Multiselect for activity level is hidden when only one option is available
> Fix multiselect placeholder

- server/script/inviteAdmin.js
- server/shared/util/Deffered.js
- server/user/user.model.js
This PR adds the option to wait for email send and is used when inviting admin from the script so we ensure the email is successfully sent before terminating the script.
> Await email send when inviting admin from script

- client/components/editor/teaching-elements/Modal/index.vue
> Fix for modal items reorder issue

- client/components/common/ActivityBrowser/SelectActivity.vue
> Fix copy activity button positioning on Outline

- client/components/common/Meta/Select.vue
> Handle console error when deselecting on selection meta

- client/components/course/TreeView/TreeGraph.vue
> Re-render tree after deleting last top level activity

- client/components/catalog/Create.vue
- client/components/course/Settings/General.vue
> Change course name field from input to textarea

- client/components/common/Select.vue
- client/components/course/Outline/Activity.vue
> Disable inheritAttrs on Activity and Select components

- client/components/course/Sidebar/Body.vue
- client/components/editor/index.vue
- client/components/editor/sidebar/index.vue
- client/components/editor/teaching-elements/Assessment/index.vue
- client/components/editor/toolbar/index.vue
- client/store/modules/course.js
- config/shared/activities-rc.js
- config/shared/activities.js
- server/shared/database/migrate.js
- server/shared/database/migrations/20181115140943-add-meta-to-teaching-element.js
- server/shared/publishing/helpers.js
- server/teaching-element/te.controller.js
- server/teaching-element/te.model.js
This reverts commit e4d36f4f55b0098830343724a33b5a7e9fb39dc5.
> Re-add teaching elements meta

- client/components/editor/structure/AddElement/SelectElement.vue
> Fix teaching element icons layout order

- build/plugins/stats.js
- package-lock.json
- package.json
- poi.config.js
This PR introduces ability to output webpack stats (`stats.json`) :tada:
> Implement `--print-stats` option

- server/script/dbSeed.js
> Fix Seed script

- server/app.js
- server/router.js
- server/user/index.js
Whitelist routes using request flow, securing server with [`helmet`](https://npm.im/helmet) :tada:
> Refactoring router

- build/plugins/brand.js
- build/plugins/output-filenames.js
- client/App.vue
- client/assets/stylesheets/main.scss
- client/main.js
- poi.config.js
This PR introduces improvements to `poi` powered build system in terms of:
- fixing bugs
- ensuring correct dist directory layout
- ensuring that 3rd party libs don't recreate their original `node_module` paths inside dist directory
> Build system improvements

- client/components/course/Outline/InsertActivity/index.vue
- client/components/course/Outline/index.vue
- client/components/course/Sidebar/Body.vue
- client/components/course/Sidebar/Header.vue
- Improved add element tooltip
- Improved sidebar UI
> Outline page improvements

- client/ElementRegistry.js
- client/components/common/tce-core/AddElement/SelectAssessment.vue
- client/components/common/tce-core/AddElement/SelectElement.vue
Registry initialization doesn't guarantee same order of elements every time, so on adding element/assessment elements will be sorted by position in configuration file.
> Sort elements

- client/components/common/Navbar.vue
> User menu UI tweak

- client/components/common/FileUpload.vue
- client/components/common/InputAsset.vue
- client/components/content-elements/tce-pdf/edit/Toolbar.vue
- client/components/content-elements/tce-video/edit/Toolbar.vue
- client/components/content-elements/tce-video/edit/index.vue
- Fixed issue with InputAsset baked in validation 
- Improved InputAsset flow
> Ability to upload video

- client/components/content-elements/tce-multiple-choice/edit/index.vue
- client/components/content-elements/tce-single-choice/edit/index.vue
> Warning message fix

- client/store/modules/activities.js
- client/store/modules/courses.js
- client/store/modules/revisions.js
Doing some _spring cleaning_ 🌬
> Use implicit `.js` file extension

- client/components/common/tce-core/ElementToolbar.vue
- client/components/common/tce-core/QuestionContainer/Controls.vue
- client/components/editor/index.vue
- client/components/editor/structure/AssessmentItem.vue
- client/components/editor/structure/Assessments.vue
- client/components/editor/structure/ContentContainers/Container.vue
- client/components/editor/structure/ContentContainers/index.vue
- Replacing controls with vuetify ones
> Editor UX improvements

- client/components/editor/structure/Exams/AssessmentGroup.vue
- client/components/editor/structure/Exams/Exam.vue
- client/components/editor/structure/Exams/GroupIntroduction.vue
- client/components/editor/structure/Exams/index.vue
- client/components/editor/structure/TesList.vue
- Resolved issues due to TesList reuse
- Added embeded mode
- Updated btns => vuetify ones
> Fixed exam TesList issues

- client/assets/stylesheets/common/_vuetify.scss
- client/components/course/Settings/Sidebar.vue
- client/components/course/Settings/UserManagement/AddUser.vue
- client/components/course/Settings/UserManagement/UserList.vue
- client/components/course/Settings/UserManagement/index.vue
- client/components/course/Settings/index.vue
- client/components/course/index.vue
- Replaced user CRUD components with vuetify ones
- Added footer
- Patches for bootstrap - vuetify compatibility
> Course settings improvements

- server/comment/comment.model.js
- server/comment/hooks.js
- server/course/course.model.js
- server/course/hooks.js
- server/revision/hooks.js
- server/revision/revision.model.js
- server/shared/database/hooks.js
- server/shared/database/index.js
- server/teaching-element/te.model.js
- server/user/user.model.js
This PR unifies internal & external hooks registration through `Model#hooks(Hooks, models)` _interface_.
> Refactor hooks registration

- .activities-rc.json.example
- client/components/auth/ResetPassword.vue
- client/components/catalog/Create.vue
- client/components/content-elements/tce-carousel/edit/Toolbar.vue
- client/components/content-elements/tce-embed/edit/Toolbar.vue
- client/components/course/Outline/InsertActivity/CreateActivity.vue
- client/components/course/Outline/NoActivities.vue
- client/components/course/Settings/CloneModal.vue
- client/components/course/Settings/General.vue
- config/shared/activities-rc.js
- config/shared/schema-parser.js
- config/shared/schema-validation.js
- package-lock.json
- package.json
This PR upgrades [`vee-validate`](https://npm.im/vee-validate) to latest version and flattens its configuration by pulling `rules` to top level configuration.
> Upgrade `vee-validate`, flatten configuration

- server/teaching-element/te.model.js
> [ISX-337] Include TE meta when clone course

- server/activity/index.js
- server/comment/index.js
- server/course/index.js
- server/revision/index.js
- Refactored routes with unnecessary wildcards
> Modified middleware routes

- client/components/editor/TeachingElement.vue
> Show snackbar upon saving TE

- client/components/course/Settings/index.vue
- client/components/course/Sidebar/Body.vue
- client/components/course/index.vue
- client/store/modules/auth.js
- client/store/modules/course.js
- client/store/modules/editor.js
- Replaced deprecated access right getters
- Removed publishing btn for content authors
> Fixed issue with access rights :wrench:

- client/api/resource.js
- client/components/editor/index.vue
> Editor issues - loader and repository not loaded

- client/components/common/Meta/Select.vue
- client/components/common/Select.vue
- package-lock.json
- package.json
This PR enables preview of activity meta Select's option image (if has one).
> Meta Select options image preview

- client/components/editor/TeachingElement.vue
- client/plugins/vuetify-snackbar/Snackbar.vue
- client/plugins/vuetify-snackbar/index.js
- added `right` position as default value for snackbar appearance
- added `primary` snackbar prop with global primary color
> Snackbar upgrade

- client/components/course/Settings/index.vue
As per page 6 of the style guide:
> Fix company name in the footer

- client/App.vue
- client/assets/stylesheets/common/_variables.scss
- client/components/common/ActivityBrowser/index.vue
- client/components/common/InputAsset.vue
- client/components/common/Meta/ColorPicker/ColorInput.vue
- client/components/common/Meta/Switch.vue
- client/components/common/Meta/index.vue
- client/components/common/Modal.vue
- client/components/common/Navbar.vue
- client/components/common/Select.vue
- client/components/content-elements/tce-brightcove-video/edit/Player.vue
- client/components/content-elements/tce-modal/edit/Modal.vue
- client/components/content-elements/tce-pdf/edit/CircularProgress.vue
- client/components/course/Revisions/EntitySidebar.vue
- client/components/course/TreeView/TreeGraph.vue
- package-lock.json
- package.json
- poi.config.js
This PR refactors vue components on client according to `stylelint` rules.
> Styles refactor according to stylelint

- package-lock.json
- package.json
:warning: Shameless plug ahead :warning:
This PR swaps `sed` magic with [`rewrite-lockfile`](https://npm.im/rewrite-lockfile).
> Replace `sed` magic with cross platform cli

- client/components/course/Outline/InsertActivity/CreateActivity.vue
> Fixed alignment for Activity create type dropdown

- client/components/editor/structure/Assessments.vue
> Show confirmation modal when canceling assessment

- client/components/course/Settings/UserManagement/AddUser.vue
- client/components/course/Settings/UserManagement/UserList.vue
> Implement autocomplete for adding people to course

- build/plugins/html-version-spec.js
- client/components/common/Footer.vue
- package.json
This PR makes version display inside `<app-footer>` live 🚀
> Show app version with codename

- client/components/catalog/Card.vue
- client/components/common/ActivityBrowser/SelectActivity.vue
- client/components/editor/index.vue
- client/components/editor/structure/AssessmentItem.vue
- client/filters.js
- client/main.js
- package-lock.json
- package.json
Refactoring global filters & exposing `_.truncate` as (global) filter 🎉
> Extract global filters to separate module

- server/activity/activity.controller.js
Proposal to include activity type inside of preview payload.
> Preview payload update proposal

- server/activity/activity.controller.js
Added `repositoryId` so that an LMS can fetch preview through the API.
> Added repositoryId to preview payload

- .gitignore
This PR removes obsolete patterns and alters existing ones to cover **all** standard pm2 & _rc_ configuration patterns. :tada:
> Cleanup gitignore

- .circleci/config.yml
- .gitignore
- README.md
This PR adds circleci config. (stacked onto #358 due to required `.gitignore` changes)
> Add circleci configuration

- client/components/catalog/Card.vue
- client/components/catalog/Container.vue
- client/store/modules/courses/getters.js
This PR introduces settings button inside repository card header :tada:
> Add direct link to course settings

- client/components/content-containers/tcc-exam/util.js
This PR fixes issue of wrongly referencing of exam elements
Depends on #376
> Fix tcc exam publishing

- client/components/content-containers/tcc-exam/util.js
- server/repository/repository.controller.js
- server/repository/repository.model.js
- server/shared/publishing/helpers.js
It is not possible to publish custom content containers because of this. Just a heads up until I find some time to fix it (or someone else does it before me :smiley_cat:).
> Cyclic dependency

- package-lock.json
- server/activity/activity.model.js
> Make sure that transaction is used when cloning

- build/plugins/brand.js
- build/plugins/clean-out-dir.js
- build/plugins/copy.js
- build/plugins/html-version-spec.js
- build/plugins/output-filenames.js
- build/plugins/stats.js
This PR adds basic jsdoc annotations to custom `poi` plugins. :lipstick:
> Add basic jsdoc annotations to poi plugins

- build/plugins/stats.js
- package-lock.json
- package.json
This PR enables poi plugin `stats` to be configured through poi configuration file. Additionally chunk sources are stripped from stats output. :surfer:
> Expose stats plugin configuration

- client/components/catalog/Card.vue
> Fixed issue with catalog card ripple upon pin click

- server/repository/index.js
> Issue with repo authorization

- README.md
- it describes what custom elements and containers are
- it links to templates which can be used to create them
> Updated README.md with an extensions block

- client/components/common/Meta/Switch.vue
- Fixed issue with label UI
- Removed placeholder
> Tweaked switch meta

- client/components/repository/Outline/InsertActivity/CopyActivity/index.vue
> Fixed issue with copy dialog not closing after completion

- client/components/repository/common/ActivityOptions.vue
- Instead of listing each type
- Insert before omitted for now
> Activity options dropdown improvements

- server/comment/hooks.js
I want to resolve #407 issue: User gets an email notification for his own comment
Before making a list of recipients we filter the author of the coment. So the person who made the comment does not recieve a email but all the others in the repository do.
Please check it out: @kjuej
> Fix the author of the comment also gets mail

- client/assets/stylesheets/common/_vuetify.scss
- client/components/common/TailorDialog.vue
- client/components/repository/Outline/InsertActivity/CreateDialog/index.vue
- client/components/repository/Outline/InsertActivity/index.vue
- client/components/repository/Sidebar/Header.vue
- client/components/repository/common/ActivityOptions.vue
- Replaced option per type with insert below / into
- Added add into btn to activity sidebar
- Improved heading
- Minors
> Improve options tooltip

- server/repository/repository.controller.js
- Last revision fetched on repo root if reloaded
- Paranoid turned off for revision user
> Resolved catalog issues

- client/store/modules/repositories/actions.js
- client/store/modules/repositories/mutations.js
- server/repository/repository.controller.js
> Pinned repositories bugfix

- client/components/repository/Outline/Activity.vue
- client/components/repository/Outline/SearchResult.vue
- client/components/repository/Outline/Toolbar.vue
- client/components/repository/Outline/index.vue
- client/store/modules/repository/actions.js
- client/store/modules/repository/mutations.js
- Extracted structure toolbar
- Created basic search cards
- Implemented goTo result functionality
> Basic activity search

- client/components/common/tce-core/AddElement/index.vue
- Match new version of component
- px => rems
> Fixed issue with element size toggle

- client/components/common/Meta/File.vue
- client/components/common/Meta/Input.vue
- client/components/common/Meta/Textarea.vue
- Validate only current meta
@kronicker ☝️
> Fixed issue with metadata validation

- nodemon.json
- package.json
This PR adds `nodemon.json` configuration file. :wrench:
> Add `nodemon` config

- client/components/common/Meta/Select.vue
Current state
- Lowered default height
- Use small chips if there are no images
> Fixed issue with select height

- server/repository/repository.controller.js
> Fixed issue with catalog ordering

- client/components/editor/ActivityContent/index.vue
- client/components/editor/Sidebar/Discussion.vue
- client/components/editor/Sidebar/ElementSidebar/ElementMeta/index.vue
- client/components/editor/Sidebar/index.vue
- client/components/repository/common/Sidebar/Discussion/Embed.vue
- client/components/repository/common/Sidebar/Discussion/index.vue
- server/activity/activity.model.js
- server/activity/hooks.js
> Support activity comments within content editor

- client/components/editor/Toolbar/ActivityActions.vue
- client/components/repository/Outline/Activity.vue
- client/components/repository/Outline/SearchResult.vue
- client/components/repository/Outline/Toolbar.vue
- client/components/repository/Outline/index.vue
- client/components/repository/TreeView/TreeGraph.vue
- client/components/repository/TreeView/index.vue
- client/components/repository/common/ActivityOptions/Menu.vue
- client/components/repository/common/ActivityOptions/Toolbar.vue
- client/components/repository/common/ActivityOptions/common.js
- client/components/repository/common/CreateDialog/index.vue
- client/components/repository/common/Sidebar/Body.vue
- client/components/repository/common/Sidebar/Header.vue
- client/components/repository/common/selectActivity.js
- client/components/repository/index.vue
- client/main.js
- client/plugins/vuetify-snackbar/index.js
- client/router.js
- client/store/modules/repository/getters.js
- client/store/modules/repository/index.js
- client/store/modules/repository/mutations.js
- package-lock.json
- package.json
- Enable selecting activity using URL (query param)
- Exposed activity id for easier activity referencing
- Added search by activity id
- Added buttons for copying id and activity URL
- Improved graph view selection
> Router based activity focus

- client/components/repository/TreeView/TreeGraph.vue
- client/components/repository/TreeView/index.vue
- Fixed bug with adding activity
- Fixed bug with activity selection (repo node)
> Fixed issues with repository graph

- poi.config.js
> Ability to use default schema

- client/store/modules/repositories/mutations.js
…ot contain tag applied with tag filter selection
> fix repository list with tag filter applied

- README.md
Completing the transition to badgen.net as sole badge provider :tada:
> Swap snyk badge to use badgen provider

- package-lock.json
- package.json
- server/shared/storage/providers/amazon.js
- server/shared/storage/providers/filesystem.js
- server/shared/storage/validation.js
Unfortunately `joi` went the way of the dodo together with `hapi`: https://old.reddit.com/r/node/comments/hfidax/hapi_will_not_be_supported_anymore_by_the_end_of, therefore, removing last bits of it from our codebase.
> Swap `joi` with `yup`

- client/components/repository/common/selectActivity.js
- client/components/repository/index.vue
- removed route watcher that caused the issue
- now uses replace instead of push so that it does not pollute the history
- code clean up
> Fixed issue with browser back button not working:

- server/shared/database/index.js
> Fix publishing

- package-lock.json
- package.json
This fixes immediate server termination on node@14.
/cc @abasic
> Fix db connection on node@14

- config/shared/activities.js
- server/activity/activity.model.js
This PR:
- fixes activities reorder on the latest schema config
- resolves #563
> Fix activities reorder on latest schema config

- client/components/system-settings/UserManagement/UserDialog.vue
This PR extends already implemented `reinvite` functionality by adding `Reinvite` button in user edit dialog
> Add reinvite button in user edit dialog
